[project]
name = "openai-chatkit-advanced-samples"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "asyncpg>=0.30.0",
    "supabase>=2.22.0",
]
